### ISSUE TITLE
custom defined object name breaks the script

### ISSUE THREAD

**Issue by zilveer** [ahabra/data-bind#5]
Hi,
custom defined object name breaks it all and nothing works.

Just open the `example.html` file and paste in the following:

```var test = {};

bind({test, prop:'age', sel:'#age'});
bind({test, prop:'description', sel:'#description'});
bind({test, prop:'carColor', sel:'#carColor', attr:'style'});
bind({test, prop:'state', sel:'#states'});
test.countries = ['mx'];
bind({test, prop:'countries', sel:'#countries'});
bind({test, prop:'language', sel:'[name="language"]'});
bind({test, prop:'hobbies', sel:'.hobbies'});
bind({test, prop:'pets', sel:'#pets', root: document.getElementById('root1')});

bind({test, prop:'squareMe', onChange: (oldv, newv)=> {
  document.querySelector('.changeUnbounded').innerText = newv * newv
}});```

and run any of the examples and i will see that the binding doesnt work.
or else, this script is good!

regards

**Comment by ahabra** [comment]
Hello Zilveer,

I was not able to reproduce the issue. However, I noticed in your example a possible concern. The `test` object should be created first. So your example could be:

```js
const test = bind({prop:'age', sel:'#age'});
bind({obj:test, prop:'description', sel:'#description'});
...
```

The `bind()` function returns the bound object.
The `obj` argument is optional. If missing, a new object is created and returned.
Note also how `test` is passed as a value for the key `obj`.
I hope that this fixes your issue, if not, please let me know.

Thank you
